apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-model
  labels:
        app: recommender-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommender-model
  template:
    metadata:
      labels:
        app: recommender-model
    spec:
      containers:
      - name: recommender-model
        image: star17/recommender-model
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: recommender-model
spec:
  selector:
    app: recommender-model
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

